import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Clip-Path Generator',
	description: 'Generated by create next app',
	icons: {
		icon: './favicon.ico',
	},
};

type LayoutPorps = {
	children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutPorps) {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
